<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Zend\\Diactoros\\' => array($vendorDir . '/zendframework/zend-diactoros/src'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Aimeos\\MW\\' => array($vendorDir . '/aimeos/aimeos-core/lib/mwlib/src/MW', $baseDir . '/Resources/Private/Extensions/ai-gettext/lib/mwlib/src/MW', $baseDir . '/Resources/Private/Extensions/ai-typo3/lib/custom/src/MW'),
    'Aimeos\\MShop\\' => array($vendorDir . '/aimeos/aimeos-core/lib/mshoplib/src/MShop', $baseDir . '/Resources/Private/Extensions/ai-typo3/lib/custom/src/MShop'),
    'Aimeos\\MAdmin\\' => array($vendorDir . '/aimeos/aimeos-core/lib/mshoplib/src/MAdmin'),
    'Aimeos\\Controller\\JsonAdm\\' => array($vendorDir . '/aimeos/aimeos-core/controller/jobs/src/Controller/JsonAdm'),
    'Aimeos\\Controller\\Jobs\\' => array($vendorDir . '/aimeos/aimeos-core/controller/jobs/src/Controller/Jobs'),
    'Aimeos\\Controller\\Frontend\\' => array($vendorDir . '/aimeos/aimeos-core/controller/frontend/src/Controller/Frontend'),
    'Aimeos\\Controller\\ExtJS\\' => array($vendorDir . '/aimeos/aimeos-core/controller/extjs/src/Controller/ExtJS'),
    'Aimeos\\Controller\\Common\\' => array($vendorDir . '/aimeos/aimeos-core/controller/common/src/Controller/Common'),
    'Aimeos\\Client\\Html\\' => array($vendorDir . '/aimeos/aimeos-core/client/html/src/Client/Html'),
    'Aimeos\\Admin\\JQAdm\\' => array($vendorDir . '/aimeos/aimeos-core/admin/jqadm/src/Admin/JQAdm'),
    'Aimeos\\' => array($vendorDir . '/aimeos/aimeos-core'),
);
